### ISSUE TITLE
@

### ISSUE THREAD

**Issue by 1qa** [dfsq/wikipediaQuickHints#2]
Tks 4 ur wikipediaQuickHints chrome ext! it makes things so much convenience but could u improve it by making it works on Wikia.com too?? Tks

**Comment by dfsq** [comment]
I was thinking about making generic extension that would allow configurable domain settings. However this is outside of the scope of the Wikipedia page action extension, because this would require making extension as browser action. Currently I don't have such intention.
Maybe it will become separate project, not Wikipedia-related.
